server:
  port: 8080
  servlet:
    context-path: /

info:
  app:
    name: '@project.artifactId@'
    description: '@project.description@'
    version: '@project.version@'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth-users?createDatabaseIfNotExist=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # altere para 'update' para criar/atualizar tabelas automaticamente
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true # mude para true se desejar ver as queries SQL no console

logging:
  level:
    root: INFO
    br.com.fiap: INFO
